[project]
name = "dit360"
description = "Generate high-fidelity 360-degree panoramic images using the DiT360 diffusion transformer model in ComfyUI."
version = "1.0.0"
license = {file = "LICENSE"} 
# classifiers = [
#     # For OS-independent nodes (works on all operating systems)
#     "Operating System :: OS Independent",
#
#     # OR for OS-specific nodes, specify the supported systems:
#     "Operating System :: Microsoft :: Windows",  # Windows specific
#     "Operating System :: POSIX :: Linux",  # Linux specific
#     "Operating System :: MacOS",  # macOS specific
#
#     # GPU Accelerator support. Pick the ones that are supported by your extension.
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
#     "Environment :: GPU :: AMD ROCm",       # AMD ROCm support
#     "Environment :: GPU :: Intel Arc",      # Intel Arc support
#     "Environment :: NPU :: Huawei Ascend",  # Huawei Ascend support
#     "Environment :: GPU :: Apple Metal",    # Apple Metal support
# ]

dependencies = ["# ComfyUI-DiT360 Dependencies", "#", "# NOTE: Loose version constraints to avoid conflicts with existing ComfyUI installations", "# DO NOT pin exact versions unless absolutely necessary", "# Core dependencies (should already be in ComfyUI)", "# torch>=2.0.0,<3.0.0  # Installed with ComfyUI, don't reinstall", "# torchvision>=0.15.0  # Installed with ComfyUI, don't reinstall", "# Hugging Face ecosystem", "transformers>=4.28.1", "diffusers>=0.25.0", "accelerate>=0.26.0", "huggingface-hub>=0.20.0", "# Model format and safety", "safetensors>=0.4.2", "# Optional dependencies (commented out by default)", "# Uncomment if needed for advanced features", "# Image processing (usually already installed)", "# pillow>=10.0.0", "# Advanced image operations", "# opencv-python>=4.8.0", "# For faster attention (optional)", "# xformers>=0.0.20  # Memory efficient attention", "# flash-attn>=2.0.0  # Flash attention 2 (requires CUDA)", "# For model quantization (future)", "# bitsandbytes>=0.41.0  # 8-bit/4-bit quantization"]

[project.urls]
Repository = "https://github.com/cedarconnor/ComfyUI-DiT360"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/cedarconnor/ComfyUI-DiT360/wiki"
"Bug Tracker" = "https://github.com/cedarconnor/ComfyUI-DiT360/issues"

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-DiT360"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

